### PR TITLE
Maintenance/review and update template

### PR DESCRIPTION
**Pull request by ryan-kipawa**

### CODE REVIEW

**Comment by ryan-kipawa** [comment]
Should we include an manual action for publishing to [TestPyPI](https://test.pypi.org/), similar to this:

https://github.com/pypa/packaging.python.org/blob/main/source/guides/github-actions-ci-cd-sample/publish-to-test-pypi.yml

Could be a useful sanity check for new package maintainers

**Review by jsmariegaard — APPROVED** [review]
Looks great - did you test if it works by using the template?

**Comment by ryan-kipawa** [comment]
Not yet, but I'll do that 😄

**Comment by jsmariegaard** [comment]
> Not yet, but I'll do that 😄

I could also have done that as review - but I am too busy right now. Sorry 🫣

**Comment by ryan-kipawa** [comment]
No worries, it was a good process for me to go through anyways. Confirmed that it's all working now 🚀

**Pull request merged**
